### ISSUE TITLE
Liquidity Chart for Individual Price Positions is Incorrect

### ISSUE THREAD

**Issue by mdr223** [pangolindex/analytics-avalanche#13]
In the accounts page I've noticed that while the liquidity chart for "All Positions" appears to be correct, selecting an individual pair position returns a graph that seems to show the total liquidity for that pair instead of your account's liquidity for that pair. I'm going to fork off of the repo and attempt to find the bug and create a fix.

**Comment by dasconnor** [comment]
Closed by #15
