### ISSUE TITLE
Liquidity shown on analytics account page is greater than removable amount on exchange

### ISSUE THREAD

**Issue by best-coder-NA** [pangolindex/analytics-avalanche#16]
Saw an issue with Pangolin Analytics today showing that I have more PNG-WAVAX liquidity than I can actually claim

Pangolin Analytics: 2.41 PNG & 0.226 WAVAX
When I go to remove liquidity: 0.77 PNG and 0.07 AVAX

https://info.pangolin.exchange/#/accounts
<img width="499" alt="Screen Shot 2021-03-22 at 9 33 13 AM" src="https://user-images.githubusercontent.com/62673755/112091217-2d636580-8b52-11eb-9a09-533468535088.png">

https://app.pangolin.exchange/#/pool
![Screen Shot 2021-03-22 at 9 52 03 AM](https://user-images.githubusercontent.com/62673755/112091204-289eb180-8b52-11eb-84ae-ac8010f37d37.png)

**Comment by bmino** [comment]
I think this was addressed in ab30bb2ab9b89f97a170cc23e416687a663d08b0? Are you still experiencing this?
