### ISSUE TITLE
Fee Charts for Pair Positions are Off

### ISSUE THREAD

**Issue by mdr223** [pangolindex/analytics-avalanche#17]
(Note: this is tied to issue #14)

Edit: I just realized I was looking at the liquidity chart(s) with my branch in the community repo which does not have the change that was merged in to address the first half of this issue.

The l~~iquidity and~~ fee charts for individual pair positions are off. ~~For liquidity it may just be an issue where the y-axis seems to be incorrect, however one interesting thing I've noticed is that switching back and forth between the fees and liquidity graphs will drastically change the y-axis for liquidity.~~

The fee charts are off due to a known issue where fees are being computed incorrectly. A PR is up in the community repo to estimate fees instead, however this change needs to also make its way into the `src/utils/returns.ts::getHistoricalPairReturns` function, which is still using the old method for computing fees.

I believe solving the latter issue will be a relatively minor change that I can address. ~~Solving the former issue related to the liquidity chart y-axis may require more investigation.~~

**Comment by bmino** [comment]
Was this sufficiently addressed in ab30bb2ab9b89f97a170cc23e416687a663d08b0?

**Comment by bmino** [comment]
please reopen if this is still happening
