### ISSUE TITLE
Compute AVAX Price With Stablecoin Pairs

### ISSUE THREAD

**Issue by mdr223** [pangolindex/analytics-avalanche#18]
(Credit to Connor for raising this)

In Uniswap's analytics code the price of ETH is computed as a function of its stablecoin pairs. At the outset of Pangolin there were not enough (any?) well established stablecoin pairs to compute the price of AVAX with, so the price of AVAX was instead set to 1 and its true price was retrieved in the frontend. Now that AVAX/DAI and AVAX/USDT are well established, we would like to revert to computing the price by using our existing stablecoin pairs. This change would simplify the logic of the analytics code and make certain computed values easier to reason about. Additionally, we would like to go through the codebase and swap all instances of "ETH" with "AVAX" to make the code even clearer.

**Comment by bmino** [comment]
Indeed! Sorry I overlooked this issue, but we made these changes last month and are now using the a weighted set of WAVAX/USDT, WAVAX/DAI and reindexing to also use WAVAX/USDT.e and WAVAX/DAI.e

**Comment by bmino** [comment]
As for switching all references to use AVAX, that hasn't happened yet and PRs are certainly welcome!
