### ISSUE TITLE
Token price chart displaying different prices when view parameters changed

### ISSUE THREAD

**Issue by nhooey** [pangolindex/analytics-avalanche#4]
The Pangolin (`PNG`) token price chart is broken, showing different prices for different views of the graph.

Look at the screenshots for the variation in the following settings:
* Candle width (**D**aily, **H**ourly)
* Duration (**1W**week, **1M**onth, **All** time)

Where the prices are different for the following moment in time:
`2021-02-17 00:00 UTC`:
* Candle: **H**, Duration: **All**: `$0.74`
* Candle: **H**, Duration: **W**: `$11.97`

![image](https://user-images.githubusercontent.com/65458/108606145-60191300-7386-11eb-93d3-d11fd8dde0be.png)
![image](https://user-images.githubusercontent.com/65458/108606155-66a78a80-7386-11eb-9fa3-be1c7bcdf3a6.png)

First referenced in [this Discord message](https://discord.com/channels/786999832027463710/786999832027463713/811707073511030834).

**Comment by bmino** [comment]
The sourcing and display logic for this has underwent significant changes in the last month. I cannot replicate this issue now. Are you still experiencing this?

![image](https://user-images.githubusercontent.com/10902767/128783985-c2fce131-ef59-4a3c-94c8-f2f873235983.png)
![image](https://user-images.githubusercontent.com/10902767/128784002-eda2d936-9f91-4a6b-9245-9af3a7deab34.png)
