### ISSUE TITLE
volunteer move to uniswap v2 fork

### ISSUE THREAD

**Issue by kmcintyre** [pangolindex/analytics-avalanche#6]
Attempting to move analytics back to uniswap fork.

Overlay analytics onto uniswap v2.
Learn something.

**Comment by HariSeldon23** [comment]
Can you expand a bit more on what features you're looking at? If you look at Uniswap v2, they introduced the following:
* ERC20 / ERC20 Pairs
* Price Oracles
* Flash Swaps
* Core/Helper Architecture
* Technical Improvements
* Path to Sustainability
* Testnet and Launch Details

In terms of Price Oracles, Pangolin has already launched a Graph subgraph here https://thegraph.com/explorer/subgraph/eldeniz/pangolin although you can see it's undeployed, you can still gain access to it programmatically here https://cchain.explorer.avax.network/address/0xefa94DE7a4656D787667C749f7E1223D71E9FD88/transactions

I think a lot of us are wanting to see more features and we're impatient, but we as a community, should see where we can help out if possible. I love the idea of Flash Swaps but I think everyone's still figuring out the best way to open up community contributions.

**Comment by kmcintyre** [comment]
Probably beyond some of my comprehension (as of right now) which makes it beyond where I'd like to start.

I see https://github.com/Uniswap/uniswap-info fork as a better option than the copy/paste of https://github.com/pangolindex/analytics.

To build trust I'd like to get analytics back to this forked version.  By overlaying analytics into fork I can play catch up so-to-speak.  Study the graph calls, audit color palette - all while bringing into the fold little improvements uniswap has made since the split.  Plus untold future uni improvements.
 
https://github.com/nwice/pangolindex-info
https://github.com/kmcintyre

**Comment by kmcintyre** [comment]
Wasn't expecting anything, so I forked uniswap info into my own repo.

Plan was to have working prototype on cloudfront this weekend with a few touch ups.

The other piece I'm working on is for the zero hack-a-thon.

**Comment by HariSeldon23** [comment]
Careful of Zero https://github.com/CodeForcer/zero-exchange-exposed

Zero hack-a-thon :) not sure if they're trying to be ironic!

**Comment by kmcintyre** [comment]
Am aware thank you!  All the same their website had some nice touches.

**Comment by kmcintyre** [comment]
Normally I don't like to use future tense with regards to software, but I will be getting to a point where some interaction with product owner of https://info.pangolin.exchange/ would be helpful.

Would like to be done this weekend for potential discussion to replace existing analytics.  There's a need to be back on the uniswap upstream.

https://github.com/nwice/pangolindex-info - pushing code in no particular order -- just working through react hooks with an eye on UI and XHR requests

http://beta.scewpt.com - may or may not be up at any particular time 

https://www.linkedin.com/in/kmsoftware/ - more info on me

**Comment by kmcintyre** [comment]
https://github.com/nwice/pangolindex-info -- hello - so spent another day on this...the colors are totally wrong etc. intentionally to abstract something descent to give back to uniswap.

**Comment by dasconnor** [comment]
Community forks are a great thing to see! I'm not sure what the action is here. Should we close this issue?

**Comment by HariSeldon23** [comment]
I'm happy if this is closed. There's no real action points from this issue :)

**Comment by kmcintyre** [comment]
Please do not close this issue.  I've put work into replacing the copy/paste repo that's outdated.

Why was the repo copy/pasted?  Why wasn't it forked?  As it exists the repo is out of date when compared to uniswap.

This work is coming forward - and will be replacing https://github.com/pangolindex/analytics

**Comment by dasconnor** [comment]
I did fork it for the initial development work. When it came time to publish, it seemed like our two projects were diverging, so I decided to go with the clean history. I appreciate the work you're doing, but I think it would probably be better to put that in its own repo. I don't think I'd support overwriting this whole repo with a replacement.
